# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField()),
                ('favs', models.IntegerField()),
                ('createtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('avatar', models.CharField(default='static/images/default.png', max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('createtime', models.DateField(auto_now=True)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='firstapp.Article')),
            ],
        ),
    ]
