# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='favs',
            new_name='likes',
        ),
    ]
