# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20161105_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='belong_to',
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default='static/images/default.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
