# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170322_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.URLField(default='images/default.png'),
        ),
    ]
