# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_comment_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
