# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20170324_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor_choice',
            field=models.BooleanField(default=False),
        ),
    ]
