# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='cate_choice',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('best', 'best')], max_length=10, null=True),
        ),
    ]
