# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0012_auto_20170326_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(default='images/default.png')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='firstapp.Article')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
    ]
