# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20170406_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='vote',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男生', '男生'), ('女生', '女生')], max_length=100, null=True),
        ),
    ]
